/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.4/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:28.0-jre")

    // Hsqldb is used in the code
    implementation("org.hsqldb:hsqldb:2.5.0")
    // The scott hsqldb files are in this jar
    implementation("net.hydromatic:scott-data-hsqldb:0.1")

    // https://mvnrepository.com/artifact/org.apache.calcite/calcite-core
    compile("org.apache.calcite:calcite-core:1.22.0")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

application {
    // Define the main class for the application
    mainClassName = "com.gerardnico.calcite.App"
}
